### ISSUE TITLE
Path for election16-county.csv

### ISSUE THREAD

**Issue by rdocking** [kjhealy/socviz#1]
Thanks for the very interesting text! Working through to section 8.2., I saw:

```
election_data <- read_csv("data/election16-county.csv")
```

This data set doesn't seem to exist within the package. I found it at:

```
https://raw.githubusercontent.com/kjhealy/viz-election/master/election16-county.csv
```

**Comment by kjhealy** [comment]
This was updated a while back; thank you for reporting it and my apologies for not closing this issue sooner.
