### ISSUE TITLE
Enable HTTPS for http://socviz.co

### ISSUE THREAD

**Issue by yihui** [kjhealy/socviz#3]
I hope you don't mind me posting the issue in this repo, but could you enable HTTPS for the website http://socviz.co? I wish to exhibit this book on the homepage of https://bookdown.org. Thanks!

**Comment by kjhealy** [comment]
Hi @yihui — sure (and thanks!). https://socviz.co should be working now.

**Comment by yihui** [comment]
Excellent! Thanks!
