### ISSUE TITLE
Compatibility problems...

### ISSUE THREAD

**Issue by cmonserr** [kjhealy/socviz#6]
I have trying to install the "socviz" package and, depending on the type of package, I have different errors:

1.- If I try to install the package directly "install.packages("socviz")", R says 
Warning in install.packages :
  package ‘socviz’ is not available (for R version 3.5.0)

2.- If I try to install the developer version "devtools::install_github("kjhealy/socviz")", R says
Error: object ‘glue_collapse’ is not exported by 'namespace:glue'

I have bought your book and try to follow it. However, I'm stuck just at the beginning because I can not install the packages that you recommend at the preface section of your book. 

Could you help me?

**Comment by kjhealy** [comment]
Hi,

Sorry you're having trouble. 

1. The `socviz` library isn't on CRAN at present, but `devtools::install_github("kjhealy/socviz")` should work. 

2. Your error looks like a temporary problem with the version of devtools you have installed. The most straightforward thing to do at this point is to install the `socviz` package locally. You can download it from my own website. There are instructions here: 

https://kieranhealy.org/blog/archives/2019/03/12/installing-socviz/

Follow the instructions for _Option 2_. Let me know if it works.

**Comment by cmonserr** [comment]
The second worked.

Thanks a lot.

Carlos
