### ISSUE TITLE
dataset election: Swapped electoral votes?

### ISSUE THREAD

**Issue by gertjanssenswillen** [kjhealy/socviz#7]
It seems that the amount of electoral votes of democrats and republicans are swapped: 

Documentation says: 

ev_dem. Electoral votes for Clinton
ev_rep. Electoral votes for Trump

Data says: 

```
election %>% summarize_if(str_detect(names(.), "ev"), sum)
# A tibble: 1 x 3
  ev_dem ev_rep ev_oth
   <dbl>  <dbl>  <dbl>
1    304    227      7
```

**Comment by kjhealy** [comment]
Thanks! Fixed.
